### ISSUE TITLE
Some question about the solver and *.slvs format

### ISSUE THREAD

**Issue by KmolYuan** [solvespace/solvespace#292]
Hello. I made a Python 3 wrapper for the solver,

+ https://github.com/KmolYuan/python-solvespace

This project is using newest source code and compile without CMake. It can made `slvs.h` be import then used simply in a Python script (shown as [PyDemo](https://github.com/KmolYuan/python-solvespace/blob/master/PyDemo.py)).

If allowed, I would like to add it to the "solver" branch.

On the other hand, I want external programs can read and write *.slvs format, with fully Link / Assemble support, then solvespace files can be generated from C or Python.

Best regard.

**Comment by Symbian9** [comment]
For the record, soon it could be used for implement SolveSpace solver in Blender 2.7x or later
* https://github.com/KmolYuan/python-solvespace/issues/2

**Comment by whitequark** [comment]
@KmolYuan The "solver" branch exists because of copyright reasons, not for technical ones. If you are aiming for integrating your Python bindings, that should be done in the "master" branch, where active development happens. Are you fine with that?

**Comment by KmolYuan** [comment]
Sure!

If it can be integrated into the CMake build process it would be better.

-----

By the way, the file [file.cpp] is using information from SK ([Sketch class]) of [SolveSpaceUI class], It seems to be unrelated to solver parts.

Is possible to separate SK and UI parts, or just using SolveSpaceUI directly to write a *.slvs format?

[file.cpp]: https://github.com/solvespace/solvespace/blob/master/src/file.cpp
[Sketch class]: https://github.com/solvespace/solvespace/blob/master/src/solvespace.h#L562
[SolveSpaceUI class]: https://github.com/solvespace/solvespace/blob/master/src/solvespace.h#L591

**Comment by whitequark** [comment]
OK. I will ask you to sign a CLA very soon and then I will be able to integrate your code. I will handle CMake and basic testing for you.

Right now the solver that is exposed via the external interface can only solve for one group, and files have many. So, the exposed solver cannot interact with files. I'm not sure what's the best way to fix this, I've not really considered the binding evolution much.

**Comment by KmolYuan** [comment]
For the file format section, maybe there should be a new external interface with the internal data format.

Because I want to put the results of the external design process into Solvespace. There would be used as auto-assemble function.

**Comment by whitequark** [comment]
> For the file format section, maybe there should be a new external interface with the internal data format.

Unfortunately the way code is currently structured, the internal C++ interface does not check many invariants, so actually exposing it as-is in Python would cause a hard to debug crash in case of misuse. Of course we want to fix that but it is by no means quick.

The UI is not scriptable either.

**Comment by whitequark** [comment]
Thank you for your contribution, and welcome. The SolveSpace project has a Contributor License Agreement; in order for me to be able to merge your changes, please sign it at https://cla-assistant.io/solvespace/solvespace. It will take only a small amount of your time.

**Comment by whitequark** [comment]
@KmolYuan Are you still interested in integrating this?

**Comment by KmolYuan** [comment]
[Python-Solvespace](https://github.com/KmolYuan/python-solvespace) project has been updated a new wrapper mechanism to [Cython](https://github.com/cython/cython) instead of SWIG at April 2019.

The old SWIG wrapper is terminated at https://github.com/KmolYuan/python-solvespace/commit/24cfed41705539f42df099bf45405b652b4a6778. They are not existed in the current version.

Wrapper source code:
+ `Cython/slvs.pxd`
+ `Cython/slvs.pyx`

Compile settings:
+ `Makefile`
+ `requirements.txt` (Python dependence)
+ `setup.py`
+ `.travis.yml`
+ `appveyor.yml`
+ `platform/patch.diff` (for Python compiler option update)

For development:
+ `__init__.py` (module expose for Python code)
+ `slvs.pyi` (stub file)
+ `test_slvs.py` (unit test)
+ `example/*.slvs` (cases in unit test)

The makefile is just used to call "`python setup.py build_ext -j0 --inplace`" and clean them up (non-essential). In the current test, Python-Solvespace can be coexist with Solvespace.

To merge them, there must be some work here:

+ [ ] Move above source code into `Cython` directory.
+ [ ] The `setup.py` file needs to adjust as https://packaging.python.org/tutorials/packaging-projects/.
+ [ ] Integrate CI tests.

Directory is as follows:

```bash
/solvespace
    /Cython
        /Python-Solvespace
            __init__.py
            slvs.pyi
            slvs.pxd
            slvs.pyx
        /platform
            patch.diff
        /tests
            __init__.py
            test_slvs.py
        setup.py
    ...
```

**Comment by whitequark** [comment]
Looks reasonable.

**Comment by KmolYuan** [comment]
There are two different ways to add this solver wrapper.

Let [solvespace] as submodule in [python-solvespace]; or integrate the wrapper into the branch (or maybe new branch) of [solvespace], then [python-solvespace] might be deprecated.

[solvespace]: https://github.com/solvespace/solvespace
[python-solvespace]: https://github.com/KmolYuan/python-solvespace

I think the former will be more convenience to publish the wrapper to PyPI with CI service. The submodule can follow `master` branch if Solvespace updated.

If the latter one, the wrapper packages still can released at a forked repository.

@whitequark Which way does this community prefer?

**Comment by whitequark** [comment]
So, there's one thing to discuss first. SolveSpace uses the GPLv3+ license and has a CLA. Are you willing to relicense the wrapper as GPLv3+ and sign the CLA? If no, the bindings unfortunately have to be separate. If yes, then I propose putting the bindings in the same repository, so that they will always be tested with the most recent SolveSpace version, and distributed together.

**Comment by KmolYuan** [comment]
OK, I will change the license of [python-solvespace] to GPLv3+.

I will fork this repository and do it at `python wrapper` branch as above plan.

[python-solvespace]: https://github.com/KmolYuan/python-solvespace

**Comment by KmolYuan** [comment]
The [PyPI](https://pypi.org) releases require user account and password from CI serves. In common way, the user name and password stored in `TWINE_USERNAME` and `TWINE_PASSWORD` environment variables of Twine.

Travis CI (Ubuntu):

```yaml
matrix:
    include:

        - os: linux
          sudo: required
          python: "3.6"
          dist: xenial
          deploy: &deploy-options
              provider: pypi
              user: $TWINE_USERNAME
              password: $TWINE_PASSWORD
              skip_cleanup: true
              skip_existing: true
              on:
                  tags: true

        - os: linux
          sudo: required
          python: "3.7"
          dist: xenial
          deploy:
              <<: *deploy-options
```

Travis CI (Mac OS):

```yaml
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [ -n "$TRAVIS_TAG" ]; then
            python3 -m pip install twine --user;
            python3 setup.py sdist bdist_wheel;
            python3 -m twine upload dist/*.whl --skip-existing;
        fi
        fi
```

AppVeyor (Windows):

```yaml
artifacts:
    - path: dist\*.whl

deploy_script:
    - IF "%APPVEYOR_REPO_TAG%"=="true" (pip install twine)
         ELSE (echo deployment has been skipped as environment variable has not matched)
    - IF "%APPVEYOR_REPO_TAG%"=="true" (twine upload dist\*.whl --skip-existing)
```

---

Here are some things to do:

+ Change path of package.
+ PyPI account of solvespace (and contributors).
+ When to release? (by tags?)
