### ISSUE TITLE
Add support for the .slvs file format to GitHub's linguist

### ISSUE THREAD

**Issue by ad-si** [solvespace/solvespace#870]
It would be cool if .slvs was an offcially supported language by GitHub. This would make it easier to find other SolveSpace projects on GitHub. A tutorial on how to add a new language can be found here: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

TLDR:

1. Add an entry to languages.yml. E.g.
  ```yaml
  SolveSpace Model:
    type: data
    color: "#FF00FF"
    ace_mode: text
    extensions:
    - ".slvs"
  ```
 2. Add sample file (e.g. bracket.slvs)
 3. Add a TextMate-compatible syntax-highlighting grammar

Maybe someone can help me with the TextMate grammar?
